include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_relative_imports
    - require_trailing_commas
    
analyzer:
  exclude:
    - lib/generated/**
    - test/**
    
  errors:
    invalid_annotation_target: ignore
