name: notely_todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc_presentation: ^1.0.0
  bloc_test: ^9.1.7
  dio: ^5.4.3+1
  drift: ^2.18.0
  drift_sqlite_async: ^0.1.0-alpha.1
  easy_localization: ^3.0.7
  either_dart: ^1.0.0
  firebase_core: ^2.31.1
  flutter_hooks_bloc: ^0.17.0
  flutter_modular: ^6.3.3
  flutter_secure_storage: ^4.2.1
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  path_provider: ^2.1.3
  path: ^1.9.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  riverpod: ^2.5.1
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  drift_dev: ^2.18.0
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  import_path_converter: ^1.0.1
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true

  assets:
  - assets/

import_path_converter:
  relative: true # Select relative path import or package import(default: false)
  ignored_files: # Add files to ignore(default: [])
    - \/test\/*