name: notely_todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  bloc_presentation: ^1.0.1
  bloc_test: ^9.1.7
  cloud_firestore: ^5.5.1
  dio: ^5.7.0
  drift: ^2.22.1
  drift_sqlite_async: ^0.2.0
  easy_localization: ^3.0.7
  either_dart: ^1.0.0
  envied: ^1.0.0
  equatable: ^2.0.7
  firebase_core: ^3.8.1
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  flutter_modular: ^6.3.4
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  mockito: ^5.4.4
  path: ^1.9.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  shimmer: ^3.0.0
  sqlite3_flutter_libs: ^0.5.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  drift_dev: ^2.22.1
  envied_generator: ^1.0.0
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  import_path_converter: ^1.0.1
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/translations/
  - fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          style: normal
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto-Medium.ttf

import_path_converter:
  relative: true # Select relative path import or package import(default: false)
  ignored_files: # Add files to ignore(default: [])
    - \/test\/*